use Project;
 
 /*每部书*/
 CREATE TABLE PKBOOK
 (BN NVARCHAR(40)NOT NULL,/*书名*/
  STHEME NVARCHAR (40)NOT NULL,/*学科主题*/
  ISBN NVARCHAR(50)NOT NULL,/*ISBN*/
  PUBITEM NVARCHAR(40)NOT NULL,/*出版发行项*/
  CPKNUM NVARCHAR(15)NOT NULL,/*中图法分类号*/
  PRIVP NVARCHAR(50)NOT NULL,/*个人责任人*/
  PRIVNP NVARCHAR(50),/*个人次要责任人*/
  FORMITEM NVARCHAR(50)NOT NULL,/*载体形态项*/
  CONSTRAINT PKBOOK_Prim PRIMARY KEY(ISBN)
  );

  /*每本书*/
CREATE TABLE PBOOK   
(CALLNUM NVARCHAR(20)NOT NULL,/*索书号*/
 ISBN NVARCHAR(50)NOT NULL foreign key references PKBOOK(ISBN),/*ISBN*/
 BARCODE NVARCHAR(15)NOT NULL,/*条码号*/
 VOLUMEISSUE NVARCHAR(10),/*年卷期*/
 COLLECT NVARCHAR(20)not null,/*馆藏地*/
 BOOKCOND NVARCHAR(20) NOT NULL /*书刊状态*/
 CONSTRAINT PBOOK_Prim PRIMARY KEY(BARCODE)
 );

 /*借阅用户*/
 CREATE TABLE PERSON
 (
  CNUM NVARCHAR(20) NOT NULL,/*证件号*/
  SNODE NVARCHAR(30)NOT NULL,/*密码*/
  CONSTRAINT PERSON_Prim PRIMARY KEY(CNUM)
  );

  /*管理员*/
   CREATE TABLE MANAGER
 (
  WNUM NVARCHAR(20) NOT NULL,/*工作号*/
  MSNODE NVARCHAR(30)NOT NULL,/*管理员密码*/
  CONSTRAINT MANAGER_Prim PRIMARY KEY(WNUM)
  ) ;
  
/*书籍评论表*/
  CREATE TABLE BOOKHAVECOMMENTS
  ( ISBN NVARCHAR(50)NOT NULL,/*ISBN*/
    COM NVARCHAR(1000),/*评价*/
    CNUM NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES PERSON(CNUM),/*证件号*/
    CONSTRAINT BOOKHAVECOMMENTS_Prim PRIMARY KEY(ISBN,CNUM)
  );
/*借阅表*/ 
 CREATE TABLE BOOKB
 ( CNUM NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES PERSON(CNUM),/*证件号*/
   BARCODE NVARCHAR(15)NOT NULL,/*条码号*/
   BTIME DATE NOT NULL,/*借书日期*/
   RTIME DATE/*还书日期*/ 
   CONSTRAINT BOOKB_Prim PRIMARY KEY(CNUM,BARCODE)
 );
